# Generated by Django 3.2.25 on 2026-05-14 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(default='home_video', max_length=50, unique=True)),
                ('video_file', models.FileField(upload_to='videos/')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='TopicContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic_name', models.CharField(max_length=100, unique=True)),
                ('video_file', models.FileField(blank=True, null=True, upload_to='topic_videos/')),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='topic_pdfs/')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
