# Generated by Django 4.1.13 on 2026-08-06 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_sitecontent_topiccontent'),
    ]

    operations = [
        migrations.AddField(
            model_name='topiccontent',
            name='video_link',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
